TuringLang/MCMCChains.jl

src/plot.jl

This does away with the precompilation warnings. Plotting functions
should continue to work as before.

Avoid loading the `Plots` package.

---

src/MCMCChain.jl
src/chains.jl
src/discretediag.jl
src/gelmandiag.jl
src/gewekediag.jl
src/heideldiag.jl
src/mcse.jl
src/plot.jl
src/rafterydiag.jl
src/stats.jl
src/utils.jl
test/diagnostic_tests.jl
test/missing_tests.jl
test/runtests.jl

This PR refactors the Chain type in MCMCChain to allow for missing values and additionally introduces unique symbols which can be used to uniquely index variable.
Related issues #16, TuringLang/Turing.jl#474, TuringLang/Turing.jl#484, TuringLang/Turing.jl#370

Refactoring of the Chain type to allow for missing values

---

README.md
src/plot.jl
test/plot_test.jl

As discussed on Slack. Here's the rationale (copied from the discussion). 
Right now the code is elegant and makes full use of the recipes API, but it’s just a little at odds with normal Plots logic. In two respects mainly: 
1. You have `densityplot` and `histogramplot` names, but in fact they’re just `density` and `histogram` that accepts a `Chain` (and adds some labels). The Plot idea is to use the same logic throughout, so you won’t have to remember so many arbitrary things, so ideally you should just write `histogram(myChain)`. But that’s a little tricky as density and histogram are `series recipes` and you’ve implemented everything as `user recipes`.
2. You have the concept of `ptype`, which is exactly what we in Plots terminology call `seriestype`. So I’d suggest reimplementing …

RFC: Reimplement plots

---

src/heideldiag.jl

A pull request to fix an issue where the `heideldiag` function printed out the full significant digits for some statistics (sometimes ~18 digits), so the buffer would wrap in a very ugly way. I defaulted to rounding to 4 digits and added some comments to the function.

Fixed rounding issue for heideldiag

---

README.md
src/plot.jl

This works now in the sense that
```julia
using Turing, StatPlots, MCMCChain
@model f(x) = begin
A ~ Normal(0,1)
B ~ Normal(0,1)
C ~ Normal(0,1)
x ~ Normal(0,1)
end
chain = sample(f(1), HMC(500,0.01,1))
chaincorner(chain, [:A, :B, :C])
```
gives
But, I really think we should align the syntax with the rest of the plotting syntax you have here. I can't 100% see the design of that so would be good with input. @trappmartin @cpfiffer 
Also, this requires a change in StatPlots so will require StatPlots 0.9, and will only work on julia-1.0+ 
That is a common issue with advanced recipes.
Finally, shouldn't the default size of those points in cornerplot not be smaller? :-O

Corner plot - close #26

---

src/chains.jl
src/plot.jl
test/plot_test.jl
test/runtests.jl

I was getting an undefined error for the `isnothing` function in `corner(chain, syms)` on Julia 1.0, so I changed it to an anonymous function. Anyone see any obvious issues here?

Fixed isnothing not defined error

---

src/MCMCChain.jl
test/diagnostic_tests.jl

Fixes support for serialization and deserialization of `AbstractChains` objects, and adds a test to make sure that everything's working right.
I've imported `Serialization`, do I need to add it to the REQUIRE file too?

Serialization/Deserialization Support

---

REQUIRE
src/MCMCChains.jl
src/plot.jl

See #37. MCMCChains will now only export (and load) `plot` if `Plots` or `StatsPlots` is loaded first. Anyone see any obvious issues with this implementation?

Remove plot loading by default

---

src/MCMCChains.jl
src/chains.jl
src/utils.jl
test/diagnostic_tests.jl

This PR changes the definition of a `Chains` object to 
```julia
struct Chains{A, T, K<:NamedTuple, L<:NamedTuple} <: AbstractChains
value::AxisArray{Union{Missing,A},3}
logevidence::T
name_map::K
info::L
end
```
Previously, `name_map` and `info` were of type `Dict`. This makes `Chains` object significantly more type stable. A new external function `setinfo(c::Chains, n::NamedTuple)` was added, which returns a new chain with `n` stored in `c.info`.
Additionally, I added some docstrings and did a little bit of tidying up.
@goedman do you see any conflicts here with anything on your end?

Added NamedTuple functionality to Chains objects

---

src/MCMCChains.jl
src/chains.jl
src/utils.jl
test/diagnostic_tests.jl

Addresses #28 and #43, and fixes broken concatenation functions. `Chains` objects now store references to `ChainSummaries`, so the math doesn't have to be redone every time `show` is called. I have also added a `chainscat` function, which adds separate chains together. This is to make it a bit easier to add separate chains together (at least on the Turing side):
```julia
chains = mapreduce(c -> sample(model, sampler), chainscat, 1:num_chains)
```
The default `show` function now prints out:
```
Object of type Chains, with data of type 500×5×3 Array{Union{Missing, Float64},3}
Iterations        = 1:500
Chains            = Chain1, Chain2, Chain3
Samples per chain = 500
internals         = a35
parameters        = a, a11, a2, a21
parameters
Mean    SD   Naive SE  MCSE  ESS …
```

Improve concatenation, improve default show function.

---

src/plot.jl

Currently the `corner` function wigs out when it's given an argument with multiple chains in it, so I've added functionality to flatten out a chain to allow it to plot.

Cornerplot fix

---

src/chains.jl
src/discretediag.jl
src/gelmandiag.jl
src/gewekediag.jl
src/heideldiag.jl
src/rafterydiag.jl
test/diagnostic_tests.jl

Addresses #52 by adding support for diagnostic functions. You can now call `gelmandiag(chn, section=:internals)` to use a specific section (defaults to `:parameters`) or `gelmandiag(chn, showall=true)` which uses all variables in the chain. `gelmandiag(chn, section=[:pooled, :internals])` should also work if you want to call multiple sections. 
This works for all the diagnostic functions.

Support sections for diagnostic functions

---

src/MCMCChains.jl
src/chains.jl
test/diagnostic_tests.jl

Adds a `set_section` function which can be used to change the `name_map` of a chain to something other than the default.  This came up over [on Discourse](https://discourse.julialang.org/t/setting-up-multiple-chains-in-turing-jl/20806/22). Hat tip to @goedman.
Usage example:
```julia
val = rand(500, 5, 1)
chn = Chains(val, ["P[1]", "P[2]", "P[3]", "D", "E"]);
chn2 = set_section(chn, Dict(:internals => ["D", "E"]))
```
`chn2` will now have `D` and `E` in `:internals` while everything else defaults to `:parameters`. You can also pass in a `NamedTuple` if you are so inclined.
Note that this requires a new assignment (`chn2 = set_section(. . .)`) since the `name_map` field is immutable.

Add set_section function

---

src/MCMCChains.jl
src/chains.jl
test/diagnostic_tests.jl
test/get_tests.jl
test/sections_tests.jl

Addresses #53 by forcing `chn[:D]` and `chn[:, "D", :]` to both return `Chains` objects. This is a request for comments, so please let me know if you don't like this change or want to add/drop things.
Example:
```julia
chn[:, "D", :]
```
```
Object of type Chains, with data of type 500×1×1 Array{Union{Missing, Float64},3}
Log evidence      = 0.0
Iterations        = 1:500
Chains            = Chain1
Samples per chain = 500
parameters        = D
parameters
Mean    SD   Naive SE  MCSE     ESS  
D 0.4872 0.2823   0.0126 0.0139 412.6237
```
and 
```julia
chn[:D]
```
```
Object of type Chains, with data of type 500×1×1 Array{Union{Missing, Float64},3}
Log evidence      = 0.0
Iterations        = 1:500
Chains            = Chain1
Samples per chain = 500 …
```

[RFC] Index functionality change

---

src/chains.jl
src/stats.jl
test/sections_tests.jl

Addresses #61 by showing the entire chain when `:parameters` is not in the section map. Also includes some miscellaneous indexing improvements.

Fix display error when :parameters doesn't exist 

---

src/MCMCChains.jl
src/chains.jl

* Fixes indexing by string, which was missed during #57 
* Removes the `Union{Missing, A}` type constraint from `Chains.value`. This should be determined on the user side, not built in.

Miscellaneous fixes

---

REQUIRE
src/MCMCChains.jl
src/sampling.jl
test/runtests.jl
test/sampling_tests.jl

This PR contains a proposed (simplified) sampling API as defined in StatsBase on top of MCMCChains.Chains objects as requested in #66.
It supports random sampling of draws in chains and sampling based on a Weights vector. This PR overloads StatsBase.sample() for that purpose and uses KernelDensity.kde() to compute a support range and associated densities. It is certainly possible to drop the KernelDensity dependency (although implicitly it is there through the density() plot).

Sampling api

---

src/chains.jl

Addresses #69 by hiding the `logevidence` field in the header if it is `missing`. Additionally, the default constructor for `Chains` sets a `logevidence` of `missing` if it is not provided.

Sets missing value as default for logevidence, and fixes header

---

REQUIRE
src/MCMCChains.jl
src/chains.jl
src/constructors.jl
test/arrayconstructor_tests.jl
test/dfconstructor_tests.jl
test/runtests.jl

Added Array and DataFrame constructors and associated tests.
These constructors are intended as being used at the back-end of mcmc workflows, thus after checking for valid samples has been completed. Both the Array and DataFrame constructors are overloaded.
Simple help is available using ?Array and ?DataFrame once MCMCChains is loaded.

Added export constructors (I used the wrong local branch name).

---

src/stats.jl

Fixes #75 by using the correct weights for the `quantile` function. I haven't removed this weirdness:
```julia
vals = Array(hcat([quantile(collect(skipmissing(c.value[:,i,:])), w) for i in names(c)]...)')
```
Since I'm planning on reworking most of these functions to use the newer chain summary format going on in the `dfchainsummary` branch.

Fix weight misspecification for quantiles

---

src/MCMCChains.jl
src/stats.jl

Exports the `hpd` function we have but have never exported. Also fixes #75 for real, until #79 goes through.

Export HPD

---

src/chains.jl
src/plot.jl
test/plot_test.jl

Addresses #81.
`pooleddensity(chn)` (a new function) will now generate a histogram (if discrete) or a density plot (if continuous) by pooling parameters together. You can replicate this behavior with the other plotting function by calling them with the keyword `append_chains = true`.
@itsdfish does this seem reasonable to you?
Example:
```julia
using MCMCChains, StatsPlots, Distributions
d = Normal()
chn = Chains(rand(d, 5000, 2, 10))
plot(chn)
```
```julia
plot(chn, append_chains=true)
```
```julia
pooleddensity(chn)
```

Allow for pooled density plots

---

src/chains.jl
src/stats.jl
src/summarize.jl

Addresses #87. The `quantile` function wasn't accepting the `sections` argument. I've also set it up so that the `show` function for a `Chains` object presents the results of the `describe` function, and not just `summarystats`. 
Example:
```julia
julia> chn
Object of type Chains, with data of type 1000×3×2 Array{Float64,3}
Iterations        = 1:1000
Chains            = 1, 2
Samples per chain = 1000
internals         = One
parameters        = Two, Three
2-element Array{ChainDataFrame,1}
Summary Statistics
│ Row │ parameters │ mean     │ std      │ naive_se   │ mcse       │ ess    │
│     │ Symbol     │ Float64  │ Float64  │ Float64    │ Float64    │ Any    │
├─────┼────────────┼──────────┼──────────┼────────────┼────────────┼────────┤
│ 1   │ Three      │ 0.503652 │ …
```

Describe bugfixes

---

Manifest.toml
src/chains.jl
src/gelmandiag.jl
test/dfconstructor_tests.jl
test/diagnostic_tests.jl
test/summarize_tests.jl

Builds on Turing master and AdvancedHMC master are failing. I think it's a good idea to remove Turing from the summarize and DataFrame constructor tests since Turing's internals has had and will maybe continue to have some changes.

Remove Turing from dataframe/summarize tests

---

src/stats.jl
src/summarize.jl

This PR supports digit specification for all the `ChainDataFrame` types used in MCMCChains.
The `digits` keyword may be a(n)
- `Integer`, which sets rounds all numerical columns to the value)
- `NamedTuple`, which only rounds the named column to the specified digits, as with `(mean=2, sd=3)`. This would round the `mean` column to 2 digits and the `sd` column to 3 digits.
- `Dict`, with a similar structure as `NamedTuple`. `Dict(mean => 2, sd => 3)` would set `mean` to two digits and `sd` to three digits.
Example:
```julia
using MCMCChains
chn = Chains(rand(500, 5, 10))
describe(chn, digits=4)
```
```julia
2-element Array{ChainDataFrame,1}
Summary Statistics
│ Row │ parameters │ mean    │ std     │ naive_se │ mcse    │ ess     │ r_hat  │
│     │ Symbol     │ Float64 │ Float64 │ Float64  │ …
```

Support digits keyword for stats functions

---

src/MCMCChains.jl
src/chains.jl
src/stats.jl
test/diagnostic_tests.jl

Allows you to do stuff like
```julia
mean(chn)
mean(chn, :x)
mean(chn, [:x, :y])
```
The above also works with `Strings`. I've also made a redundant `Chains` constructor a little more helpful by converting a 2d array to a 3d one, so you don't have to make an AxisArray or a 3d array yourself if you're passing in custom values.

Added mean function

---

src/MCMCChains.jl
src/chains.jl
test/diagnostic_tests.jl

Addresses #116 by adding the function `set_names`, which accepts a `Chain` and a `Dict` and returns a new chain with the names replaced. Usage example:
```julia
using MCMCChains
chn = Chains(
rand(100, 5, 5), 
["one", "two", "three", "four", "five"], 
Dict(:internals => ["four", "five"])
)
set_names(chn,  Dict(["one" => "ONE", "five" => "FIVE"]))
```
This returns a new chain, like the following:
```julia
Object of type Chains, with data of type 100×5×5 Array{Float64,3}
Iterations        = 1:100
Chains            = 1, 2, 3, 4, 5
Samples per chain = 100
internals         = four, FIVE
parameters        = two, ONE, three
2-element Array{ChainDataFrame,1}
Summary Statistics
│ Row │ parameters │ mean     │ std      │ naive_se  │ mcse       │ ess     │ r_hat    │
│     │ …
```

Add name change function

---

src/MCMCChains.jl
src/chains.jl
src/discretediag.jl
src/gelmandiag.jl
src/gewekediag.jl
src/heideldiag.jl
src/plot.jl
src/rafterydiag.jl
test/diagnostic_tests.jl

Addresses #110. Users can now pass in the `sorted=false` keyword argument to `Chains` constructors, which prevents them from being sorted. This is the important one -- the current default is to sort all the parameters when they are constructed. 
You can also pass `sorted=false` to all the plotting and summary functions (`plot(chain, sorted=false)`) which is more cosmetic.

Allow users to disable sorting

---

src/summarize.jl

Addresses #117. The issue appears to have been a case where IJulia was trying to convert a `Vector{ChainDataFrame}` to a `Vector{ChainDataFrame}`, but there was no function to handle this. I added a corner-case function and it seems to work fine on my build.

Fix IJulia display error

---

src/chains.jl
src/constructors.jl
src/stats.jl

Some additional clean-up and bug fixing for #110. The `name_map` wasn't being sorted when `sort(chain)` was called, which lead to cases where the chain was not sorted but the output was.

Fixed sorting for display functions

---

src/chains.jl
src/summarize.jl

Addresses #126 by fixing deprecated behavior in DataFrames.jl. This PR also fixes a minor bug where mutable name maps like a `Dict` were being mutated by the `Chains` constructor.

Fixes DataFrames indexing

---

README.md

I had trouble finding `set_names` and noticed it was not in the documentation.

Add set_names to README

---

src/chains.jl

This fixes a bug where multivariate variables that were substrings of another were combined. For example, if a variable `theta[1]` and a variable `eta[1]` were in the `Chains`, then calling `get` with `flatten=false` would give an `eta` with both the values of `eta` and of `theta`.

Don't merge variables that are substrings

---

Project.toml
src/chains.jl

`vcat(chain1, chain2)` often did not do what you wanted it to, which is unquestioningly stick the samples of `chain2` on the bottom of the samples of `chain1`. I've made it actually possible to use `vcat` under normal circumstances.

Fix chain concatenation.

---

test/serialization_tests.jl

Not sure if it this PR should be merged, since `resume` will be exported and its behaviour will change once https://github.com/TuringLang/Turing.jl/pull/954 is merged. Nevertheless, IMO it's problematic that currently due to this test error none of the subsequent tests are run, which makes it impossible to ensure that new PRs such as https://github.com/TuringLang/MCMCChains.jl/pull/145 do not introduce any new test failures.

Fix test of `resume`

---

Project.toml
src/chains.jl
src/discretediag.jl

For stacking vectors `v` of vectors or matrices, `reduce(hcat, v)` is usually more efficient than `hcat(v...)`, due to the optimized implementation in https://github.com/JuliaLang/julia/blob/89a51fb98485219680c7106e94cf75fd8069f3f8/base/abstractarray.jl#L1375-L1379 (see also the discussion in https://github.com/JuliaLang/julia/issues/21672).
A simple benchmark demonstrates the performance increase with `reduce`:
```julia
using BenchmarkTools
f(x) =  Array(hcat(v...)')
g(x) = copy(reduce(hcat, x)')
u = [rand(128) for i in 1:1000]
@btime f($u)        # 506.439 μs (9 allocations: 1.95 MiB)
@btime g($u)        # 365.840 μs (4 allocations: 1.95 MiB)
v = [rand(1000) for i in 1:128]
@btime f($v)        # 529.852 μs (9 allocations: 1.95 MiB)
@btime g($v)        # 272.787 μs (4 allocations: 1.95 …
```

Use reduce instead of splatting

---

src/chains.jl

This PR removes some redundant code in the constructors of `Chains`.

Simplify constructors

---

src/chains.jl

Another performance improvement, according to the following benchmark:
```julia
using BenchmarkTools
f(x) = cat(vcat([x[:, :, j] for j in 1:size(x, 3)]...), dims=3)
g(x) = reshape(permutedims(x, [1, 3, 2]), :, size(x, 2), 1)
a = rand(1000, 5, 10)
@btime f($a) # 162.962 μs (42 allocations: 1.15 MiB)
@btime g($a) # 43.850 μs (9 allocations: 391.17 KiB)
b = rand(1000, 100, 100);
@btime f($b) # 157.489 ms (226 allocations: 228.89 MiB)
@btime g($b) # 36.954 ms (9 allocations: 76.29 MiB)

Use permutedims

---

.gitignore
Project.toml
src/MCMCChains.jl

Adds a dependency on `AbstractMCMC`, which handles some upstream abstract types for `MCMCChains`. No real functional change.

Move to AbstractMCMC backend

---

Project.toml
src/chains.jl
test/diagnostic_tests.jl
test/summarize_tests.jl

This PR makes it so that chain parameters are no longer sorted by default -- any packages that relied on MCMCChains using natural sort order will need to pass `sorted=true` in their `Chains` call in order to keep current behavior.
As per @goedman's suggestion, I have also incremented the version number to 1.0 since MCMCChains is relatively stable at this point.

Remove chain sorting by default

---

test/missing_tests.jl

This PR avoids tests `x ≈ 0` since according to the documentation it
> is equivalent to x == 0 since the default atol is 0. In such cases, you should either supply an appropriate atol (or use norm(x) ≤ atol) or rearrange your code
and sets a random seed, to hopefully fix the spurious test error on Julia 1.1.

Avoid testing x ≈ 0

---

Project.toml
src/stats.jl
src/summarize.jl
test/summarize_tests.jl

Fixes https://github.com/TuringLang/Turing.jl/issues/1132, which was caused by the new display method blindly merging `NamedTuples` without preserving row ordering. It's a minor fix, so I'll merge it once tests pass.

Fixes sorting bug

---

src/dataframes-compat.jl
test/dfconstructor_tests.jl

Allows you to convert a `ChainDataFrame` to a `DataFrame` if you have `DataFrames` loaded. 
```julia
val = rand(1000, 5, 4)
chain = Chains(val)
cdfs = describe(chain)
dfs = DataFrame(cdfs)
df1 = DataFrame(cdfs[1])
df2 = DataFrame(cdfs[2])
```

Add DataFrame(::ChainDataFrame) constructor

---

src/MCMCChains.jl
src/chains.jl
src/constructors.jl
src/dataframes-compat.jl
src/gewekediag.jl
src/heideldiag.jl
src/rafterydiag.jl
src/stats.jl
src/summarize.jl
src/utils.jl
test/arrayconstructor_tests.jl
test/dfconstructor_tests.jl
test/diagnostic_tests.jl

This PR contains the following changes:
- It adds an unexported `concretize` method that can be used to transform a `Chains`, `AbstractDataFrame`, or (possibly nested) `AbstractArray` with element types that are not concretely typed (such as `Real` or `Union{Missing,Float64}`) to a version with concretely typed element types if possible (clearly it can be type stable only if all element types are already concretely type in which case it just returns the input)
- It adds separate functions to transform a `Chains` to a matrix, a vector of scalars, a vector of vectors, and a vector of matrices and makes use of these functions in the `Array` constructor
- It removes an abstract field in `Chains` by adding an additional type parameter, which, e.g., makes the functions in the last point …

Add `concretize` and fix https://github.com/TuringLang/MCMCChains.jl/issues/189

---

.travis.yml

I noticed that we run a ridiculous amount of tests. IMO testing with the LTS, stable, and latest Julia versions should be sufficient.

Test only on LTS, stable, and master

---

README.md
src/chains.jl
src/constructors.jl
src/discretediag.jl
src/gelmandiag.jl
src/gewekediag.jl
src/heideldiag.jl
src/plot.jl
src/rafterydiag.jl
src/stats.jl
src/summarize.jl
test/arrayconstructor_tests.jl
test/missing_tests.jl

This PR removes the `showall` keyword argument, instead one has to specify `sections = nothing` now. Moreover, somehow the previously merged PR reintroduced some `digits` keyword arguments which are removed in this PR as well.

Remove `showall` and reintroduced `digits` keyword arguments

---

Project.toml
src/summarize.jl

internal _to_matrix function since the source is already an Array
so the operation should really be a noop. Furthermore, the implied
type piracy causes issues in other packages.
Closes #233

Change convert(::Type{Array}, ::Vector{<:ChainDataFrame}) to the

---

Project.toml
src/mcse.jl
src/stats.jl

This PR handles chains with a small number of non-missing samples in a nicer way. Similar to ESS, no error
is thrown but `missing` is returned. The previous check was not sufficient since it was not based on
the number of non-missing samples but on the number of all samples.

Return `missing` in `mcse_bm` instead of throwing an error

---

Project.toml
src/MCMCChains.jl

Fixes a bug introducing when deprecating `read` and `write`. Instead of overloading Base.read and Base.write we accidentally added new MCMCChains.read and MCMCChains.write methods.

Fix deprecated `read` and `write`

---

Project.toml
src/summarize.jl
test/summarize_tests.jl

Fixes #244. The buggy function was actually identical to the one below it, so I just mapped them together.

Fix ChainDataFrame indexing with Colon

---

docs/Project.toml
docs/make.jl
docs/src/gadfly.md
src/MCMCChains.jl

I have been working on moving the Gadfly plotting functionality from my [package](https://github.com/rikhuijzer/TuringPlots.jl) into MCMCChains.jl. However, I figured that I was basically
1. Catching calls to `Gadfly.plot(chn::Chains, args...; vargs..., filter=nothing)`
1. Converting `chn` to `df::DataFrame`
1. Applying `filter` to `df`
1. Invoking `Gadfly.plot(df, args...; vargs...)`
So, most of this could be replaced by using the DataFrames constructor provided by MCMCChains.jl. Since this is easy in use, but can be hard to figure out, I've added a few examples to the docs. 
Some examples from the generated documentation:
I wonder if parts of these examples should be implemented in `src`. I don't think so given the relative easy of use, but am not sure about it. 
What would possibly be …

Add Gadfly examples

---

Project.toml
src/tables.jl
test/tables_tests.jl

This PR fixes #268 and https://github.com/fonsp/Pluto.jl/issues/868 by correctly implementing `Tables.rows` in terms of `Tables.columntable`.
Because the optional interface methods `Tables.namedtupleiterator` and `Tables.rowtable` were previously implemented to forward to `Tables.columntable` instead of going through the default `Tables.rows` approach, with this change, they no longer are necessary to get the performance boost and have been removed.
Edit: I have verified that Pluto correctly displays `Chains` and `ChainDataFrame` objects with this PR.

Fix implementation of Tables row interface

---

Project.toml
src/plot.jl

To avoid confusion such as in https://julialang.slack.com/team/U9AHT3YM7. Apparently this is also the standard in ArviZ.

Trim density and histogram plots

---

Project.toml
test/runtests.jl

AxisArrays works now on Julia 1.7 thanks to https://github.com/JuliaArrays/AxisArrays.jl/pull/201.

Bump AxisArrays version (Fixes Julia 1.7)

---

Project.toml
docs/src/getting-started.md
src/sampling.jl
test/sampling_tests.jl

Fixes #223. This came up also in https://github.com/TuringLang/TuringTutorials/pull/296.

Fix sampling from multiple chains

---

docs/src/stats.md
src/stats.jl

`hpd` is exported but there is no documentation for it. Please review the docstring for accuracy before merging.

add docstring for `hpd`

---

Project.toml
src/chains.jl
src/utils.jl
test/diagnostic_tests.jl

Fixes https://github.com/TuringLang/MCMCChains.jl/issues/396.

Better support for `AbstractString`

---

Project.toml
src/chains.jl

Adds proper escaping for indexing in `namesingroup`, hence adding support for stuff like `chain[:, Symbol("A[1]"), :]`.

Escape regex in namesingroup properly

---

Project.toml
src/stats.jl

In some scenarios where the chain is producing weird values, we can easily run into issues with some of the statistics we compute in `show`, which means that `show` simply breaks. This can be both very annoying and confusing. IMO `show` shouldn't break just because we have numerical issues for _one_ of the computations.
This PR adds a `try`/`catch` around the problematic computations, so that `show` can still work even if some of the statistics fail to compute.

Allow show to function properly even if some statistic computations fail

---

src/chains.jl
src/utils.jl
test/sections_tests.jl

Addresses https://github.com/TuringLang/MCMCChains.jl/issues/443

keep parameter order

---

Project.toml

PR #316 introduced new functionality but incorrectly bumped the patch version. This re-releases it as 7.1.0 to follow semantic versioning.

Re-release 7.0.1 as 7.1.0 to follow semantic versioning

---

Project.toml
docs/Project.toml
src/chains.jl
test/concatenation_tests.jl

concatenate sampler states from chains

---

Project.toml
src/MCMCChains.jl
src/chains.jl
test/concatenation_tests.jl

```julia
julia> using MCMCChains
julia> chn = Chains(
rand(10, 3, 1),
["a", "b", "c"],
info = (
start_time = 1,
stop_time = 2,
samplerstate = "state1",
otherinfo = "info1",
),
)
julia> # Current version
chainscat(chn).info
(otherinfo = "info1", start_time = 1, stop_time = 2, samplerstate = "state1")
julia> # This PR
chainscat(chn).info
(otherinfo = "info1", start_time = [1], stop_time = [2], samplerstate = ["state1"])
```
Firstly, this is consistent with standard Julia concatenation behaviour which creates singleton arrays:
```julia
julia> vcat(1)
1-element Vector{Int64}:
1
```
More importantly, this is needed to differentiate the output of `sample(model, spl, N)` from `sample(model, spl, MCMCThreads(), N, 1)` so that the save/resume interface in Turing.jl is coherent.
With this PR + …

Make `chainsstack([c])` put info fields into vectors
