TuringLang/MCMCChains.jl

.travis.yml
README.md
REQUIRE
src/MCMCChain.jl
src/plot.jl
test/plot_test.jl
test/runtests.jl

Improved plotting capacities for MCMCChain.
TODO: 
- add documentation on `colordim`
- check if creating `plot` alias functions is problematic

Refactoring of the plotting functions of MCMCChain

---

test/diagnostic_tests.jl

Minor updates to the testing suite, to address an indexing problem.

Added more specific indexing tests.

---

src/stats.jl

Minor fix to address a deprecation warning for `quantile`.

Fixed quantile deprecation warning.

---

src/chains.jl
src/plot.jl

Minor update to make #50 work a little better. I've also changed the default chain name from "Chain1" to just the integer 1. Makes everything look prettier.

Label fixes

---

src/stats.jl

Addresses #58. The `mcse_bm` function doesn't work with less than 200 samples, so I've added argumentation to the `summarystats` function which removes the ESS and MCSE columns when they cannot be computed. The user is provided a warning to that effect:
```julia
show(chn)
```
```
Object of type Chains, with data of type 150×5×1 Array{Union{Missing, Float64},3}
Log evidence      = 0.0
Iterations        = 1:150
Chains            = 1
Samples per chain = 150
parameters        = P[1], P[2], P[3], D, E
┌ Warning: Chain iterations are < 200, MCSE and ESS cannot be computed.
└ @ MCMCChains ~/.julia/dev/MCMCChains/src/stats.jl:264
parameters
Mean    SD   Naive SE
D 0.5141 0.2815   0.0230
E 0.5058 0.2954   0.0241
P[1] 0.4794 0.2873   0.0235
P[2] 0.4686 0.2766   0.0226
P[3] …
```

Catch summarystats display errors

---

Manifest.toml
Project.toml
test/runtests.jl

Adds a `Project.toml` file to prepare this repo for the package registry switchover ([see this](https://discourse.julialang.org/t/switching-package-registration-systems-on-monday/22677?u=cpfiffer) for more info).

Add Project.toml

---

src/chains.jl
test/diagnostic_tests.jl

Fix size function

---

Project.toml

Increments the version number for subsequent release.

Increment version number to 0.3.9

---

Project.toml

As requested [here](https://github.com/JuliaRegistries/General/pull/3065#issuecomment-526535924).

Add Julia compatibility.

---

Project.toml
test/sampling_tests.jl
test/serialization_tests.jl

Plots was in the project file but wasn't used. It's a fairly heady dependency so would be avoid since it isn't needed. I also fixed the tests for the changes to Turing and put a version requirement on Turing.

Remove Plots and fix tests

---

Project.toml
src/chains.jl

Allows for automatic merging to General.

Add upper bounds to dependencies

---

src/plot.jl

Fixes https://github.com/TuringLang/MCMCChains.jl/issues/107.
With this PR the example from the issue
```julia
using MCMCChains,StatsPlots
n_iter = 500;
n_name = 3;
n_chain = 2;
val = randn(n_iter, n_name, n_chain) .+ [1, 2, 3]';
val = hcat(val, rand(1:2, n_iter, 1, n_chain));
chn = Chains(val)
p = plot(layout=2)
density!(p,chn[:Param1],subplot=1)
density!(p,chn[:Param2],subplot=2)
```
produces the desired result

Do not define layout of single plots

---

src/chains.jl

This is just something I ended up with while playing around with the code for a bit, not sure if it's useful at all.
The PR reduces the number of allocations but the timings do not improve in a simple benchmark (probably due to the fact that the type of `name_map` can not be inferred):
```julia
using BenchmarkTools
chain = Chains(rand(10_000, 5, 4), ["Param$i" for i in 1:5], Dict(:parameters => ["Param$i" for i in 1:3], :internals => ["Param$i" for i in 4:5]))
@btime Chains($chain, $([:parameters, :internals])) # 217.673 μs (53 allocations: 1.53 MiB)
@btime Chains($chain, $((:parameters, :internals))) # 220.935 μs (33 allocations: 1.53 MiB)

Update implementation of how sections are extracted

---

src/chains.jl
test/diagnostic_tests.jl

Fixes an incorrect constructor with vector of vectors. Should fix https://github.com/PumasAI/Pumas.jl/pull/770.

Fix constructor with vector of vectors

---

src/chains.jl

This PR removes definitions of `chainscat`, `hcat`, and `vcat` for `AbstractChains` since they are duplicates of the implementation in `AbstractMCMC`.

Remove redundant methods

---

Project.toml
src/stats.jl
src/summarize.jl
test/summarize_tests.jl

This PR removes `handle_funs` and `merge_cdf` which are not needed.

Remove some functions

---

.travis.yml
Project.toml
src/plot.jl
src/stats.jl
src/summarize.jl
src/utils.jl
test/plot_test.jl

This PR fixes https://github.com/TuringLang/MCMCChains.jl/issues/187.

Fix Array conversion of ChainDataFrame

---

Project.toml
src/utils.jl
test/arrayconstructor_tests.jl

See https://github.com/TuringLang/Turing.jl/pull/1175.

Concretize for mix of integers, floats, and missing

---

Project.toml

Forgot to include version bounds in #193 .

Add compat for Tables/TableTraits

---

Project.toml

See https://github.com/TuringLang/Turing.jl/issues/1220.

Correctly specify AxisArrays compatibility

---

src/MCMCChains.jl
src/chains.jl
test/diagnostic_tests.jl

Add `setrange` and `resetrange` methods.
@torfjelde

Add `setrange` and `resetrange`

---

src/stats.jl

This should be more natural to understand if the info is printed.

lower before upper in HPD

---

test/rstar_tests.jl
test/runtests.jl

It seems there are some random test errors in the R star tests, maybe they can be fixed by setting a seed.

Set random seed

---

Project.toml
src/summarize.jl
test/summarize_tests.jl

Fixes https://github.com/TuringLang/MCMCChains.jl/issues/250.

Use `tf_borderless` for PrettyTables >= 0.10

---

test/get_tests.jl

Addresses https://github.com/TuringLang/MCMCChains.jl/pull/254#issuecomment-733557643.

Fix key test for `get`

---

README.md
docs/src/getting-started.md
src/chains.jl
src/rstar.jl

Now that the docs are visible online, I spotted a few minor mistakes and that the image in the README is broken. Also, I've added a few more doctests.

Fix README.md and add a few more doctests

---

Project.toml
src/constructors.jl
src/utils.jl
test/arrayconstructor_tests.jl

Fixes https://github.com/TuringLang/MCMCChains.jl/issues/317.

Fix construction of Array from empty chains

---

docs/Project.toml
docs/make.jl
docs/src/gadfly.md
docs/src/makie.md
src/chains.jl

Reasonably simple Makie.jl example. I aimed to write down some code to help people get started and allow them to fine-tune it to their use-case.
Currently, the plot looks like

Add Makie.jl example

---

Project.toml
src/plot.jl
src/stats.jl
test/diagnostic_tests.jl

Fix `autocor`

---

src/chains.jl

See #371. I accidentally closed it and cannot reopen it, because I force pushed 0 commits.

return missing directly

---

Project.toml
src/plot.jl
test/plot_test.jl

Fixes for `corner`

---

Project.toml

Forgot to bump the version number in #466

Bump patch version to v6.0.7

---

.github/workflows/Docs.yml
.github/workflows/DocsNav.yml
docs/Project.toml
docs/make.jl

Using [Turing Actions](https://github.com/TuringLang/actions) for Documentation and global Turing Navigation bar!
Reference: https://github.com/TuringLang/actions/issues/12

Documentation and Turing Navigation CI improvement
